import Head from "next/head";

import styles from "../styles/Home.module.css";
import Navbar from "../components/navbar";
import Body from "../components/body";
import Projects from "../components/projects";
import Footer from "../components/footer";

export default function Home() {
  return (
    <div className="text-light app">
      <Head>
        <title>Portfolio John Victor Cesa</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
        <link
          href="https://fonts.googleapis.com/css2?family=Roboto&display=swap"
          rel="stylesheet"
        ></link>
      </Head>
      <Navbar />
      <Body />
      <Projects />
      <Footer />
    </div>
  );
}
