import Head from "next/head";

import styles from "../styles/Home.module.css";
import Navbar from "../components/navbar";
import Body from "../components/body";
import Projects from "../components/projects";
import Footer from "../components/footer";

export default function Home() {
  return (
    <div className="text-light">
      <Head>
        <title>Portfolio John Victor Cesa</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />
      <Body />
      <Projects />
      <Footer />
    </div>
  );
}
