import Head from "next/head";
import { AiFillLinkedin, AiFillGithub } from "react-icons/ai";
import styles from "../styles/Home.module.css";

export default function Home() {
  return (
    <div className="text-light">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="container mb-5 ">
        <div className="body-container">
          <main>
            <div className="container">
              <h3 className="display-5 text-center mt-3">
                Bem vindo a minha página de portfólio
              </h3>
              <div className="mt-5 mb-5 content-body">
                <p className="text-center mt-4">
                  Sou um desenvolvedor que tem foco em desenvolver soluções de
                  software para diversos escopos.
                </p>
              </div>
              <div className="text-center mb-4">
                <h4 className="display-5">
                  Entre em contato por outras plataformas
                </h4>
                <button className="btn btn-outline-dark mx-1">
                  <AiFillGithub size={40} />
                </button>
                <button className="btn btn-outline-primary mx-1">
                  <AiFillLinkedin size={40} />
                </button>
              </div>
              <div className="direct-contact container text-center">
                Entre em contato por email: <b>joaovictorcsatu@gmail.com</b>
              </div>
            </div>
          </main>
        </div>
      </div>
    </div>
  );
}
